# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:

custom_event_handler:
  # triggereable entities are in this list
  entities:
    - input_boolean.pump_anomaly:
        # event triggered
        - ALERT:
            # the actions list (may be empty)
            actions:
              - platform: EVENT
                label: "Spegni irrigazione"
                value: "spegniIrrigazioneEvent"

kafka_producer:
  ip_address: localhost
  port: 9092
  topic: HASSIO

kafka_consumer:
  ip_address: localhost
  port: 9092
  topic: TOSYSTEM_112233

input_text:
  system_code:
    name: Identificativo Sistema
    initial: "112233"

input_boolean:
  pump:
    name: Pompa
    initial: false
  pump_line_1:
    name: Linea 1
    initial: false
  pump_line_2:
    name: Linea 2
    initial: false
  pump_anomaly:
    name: Simula Anomalia pompa
    initial: false

binary_sensor:
  platform: template
  sensors:
    anomaly:
      friendly_name: Anomalie
      device_class: problem
      value_template: >-
        {% if is_state('input_boolean.pump_anomaly', 'on')
        %}
          on
        {% else %}
          off
        {% endif %}
    pump_state:
      friendly_name: Pompa
      device_class: power
      value_template: >-
        {% if is_state('input_boolean.pump', 'on')
        %}
          on
        {% else %}
          off
        {% endif %}
    line_1_state:
      friendly_name: Linea 1
      device_class: power
      value_template: >-
        {% if is_state('input_boolean.pump_line_1', 'on')
        %}
          on
        {% else %}
          off
        {% endif %}
    line_2_state:
      friendly_name: Linea 2
      device_class: power
      value_template: >-
        {% if is_state('input_boolean.pump_line_2', 'on')
        %}
          on
        {% else %}
          off
        {% endif %}

tts:
  - platform: google_translate

group: !include groups.yaml
# automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

automation:
  - alias: "Pump Line 1 on"
    trigger:
      platform: state
      entity_id: input_boolean.pump_line_1
      to: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_line_2
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.pump
      - event: TO_OUTBOUND_EVENT
        event_data:
          entityId: input_boolean.pump_line_1
          type: NOTICE
          message: "Irrigazione Linea 1 Accesa"
  - alias: "Pump Line 1 off"
    trigger:
      platform: state
      entity_id: input_boolean.pump_line_1
      to: "off"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_line_1
      # invocare un evento interno invece che direttamente l'outbound. Prevedere anche uno switch se abilitare o meno l'evento
      - event: TO_OUTBOUND_EVENT
        event_data:
          entityId: input_boolean.pump_line_1
          type: NOTICE
          message: "Irrigazione Linea 1 Spenta"
  - alias: "Pump Line 2 on"
    trigger:
      platform: state
      entity_id: input_boolean.pump_line_2
      to: "on"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_line_1
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.pump
      - event: TO_OUTBOUND_EVENT
        event_data:
          entityId: input_boolean.pump_line_2
          type: NOTICE
          message: "Irrigazione Linea 2 Accesa"
  - alias: "Pump Line 2 off"
    trigger:
      platform: state
      entity_id: input_boolean.pump_line_2
      to: "off"
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_line_2
      # invocare un evento interno invece che direttamente l'outbound. Prevedere anche uno switch se abilitare o meno l'evento
      - event: TO_OUTBOUND_EVENT
        event_data:
          entityId: input_boolean.pump_line_2
          type: NOTICE
          message: "Irrigazione Linea 2 Spenta"
  - alias: "simula anomalia"
    trigger:
      platform: state
      entity_id: input_boolean.pump_anomaly
      to: "on"
    action:
      - event: TO_OUTBOUND_EVENT
        event_data:
          entityId: input_boolean.pump_anomaly
          type: ALERT
          message: "Si è verificata un'anomalia sulla pompa"
  - alias: "Spegni irrigazione event"
    trigger:
      platform: event
      event_type: spegniIrrigazioneEvent
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_line_1
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_line_2
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.pump_anomaly
  - alias: Hassio start routine
    trigger:
      event: start
      platform: homeassistant
    action:
      - delay: 00:00:30
      - event: kafka_start_consuming
